/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-05-16 07:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;

public final class Jsp0516_005fdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	String hello = "Hello!";
	String world = "World!";
	
	public int add (int a, int b) {
		return a+b;
	}


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Jsp0515_Ncstest.html", Long.valueOf(1557989192706L));
    _jspx_dependants.put("/Jsp0514_form.html", Long.valueOf(1557970997343L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>가빈이의 아무것도 모르는 코딩 연습</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>날짜/시간 출력</h3>\r\n");
      out.write("\r\n");


Date today = new Date();
SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd");
SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>현재 날짜 : ");
      out.print(  date.format(today) );
      out.write(" </h3>\r\n");
      out.write("\r\n");
      out.write("<h3>현재 시간 : ");
      out.print( time.format(today) );
      out.write("</h3>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>íì ê°ì</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<form action=\"Ncstest\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ì´ë¦</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"mbname\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ìì´ë</th> \r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"mbid\"> <a href=\"#\">ì¤ë³µíì¸</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ë¹ë°ë²í¸</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"mbpw\"> 6ì ì´ì</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ë¹ë°ë²í¸ íì¸</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"mbpw_re\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ë¹ë°ë²í¸ íí¸/ëµë³</th> \r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select style=\"width : 173px; height : 21px; \" name=\"pwhintans\" id=\"pwhintans\" >\r\n");
      out.write("\t\t\t\t\t            <option value=\"\">ì ííì¸ì</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"30\">ì¡¸ìí ì´ë±íêµ ì´ë¦ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"31\">ì ì¼ ì¹í ì¹êµ¬ì í¸ëí° ë²í¸ë?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"32\">ìë²ì§ ì±í¨ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"33\">ì´ë¨¸ë ì±í¨ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"34\">ì´ë¦´ ì  ë´ ë³ëªì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"35\">ê°ì¥ ìë¼ë ë¬¼ê±´ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"36\">ì¢ìíë ëë¬¼ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"37\">ì¢ìíë ìê¹ì?</option>\r\n");
      out.write("\t\t\t\t\t            <option value=\"38\">ì¢ìíë ììì?</option>\r\n");
      out.write("\t\t\t\t\t        </select>\r\n");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <th>ëµë³</th>\r\n");
      out.write("                    <td><input type=\"text\" name=\"pwhintans\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ì´ë©ì¼</th>\r\n");
      out.write("                    <td><input type=\"text\" name=\"email\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ì íë²í¸</th>\r\n");
      out.write("                    <td><input type=\"text\" name=\"cell\" inputmode=\"tel\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ë©ì¼/sns ì ë³´ ìì </th>\r\n");
      out.write("                    <td>\r\n");
      out.write("\t\t\t            <label for=\"info\"></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"info\" name=\"info\" value=\"ìì \">ìì \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"info\" name=\"info\" value=\"ìì ê±°ë¶\" checked>ìì ê±°ë¶\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ê´ì¬ë¶ì¼</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"ìë\"> ìë\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"ìë\"> ìë\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"ë¡ì¤í\"> ë¡ì¤í\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"í¸ëëë¦½\"> í¸ëëë¦½\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"ìì¤íë ì\"> ìì¤íë ì\r\n");
      out.write("                 \t\t <input type=\"checkbox\" name=\"interest\" value=\"ì°½ì\"> ì°½ì\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t    <hr>\r\n");
      out.write("\t\t    \t<div style =\"text-align : center;\">\r\n");
      out.write("\t\t\t   \t<input type=\"submit\" value=\"íìê°ì\">\r\n");
      out.write("                <input type=\"reset\" value=\"ì·¨ì\">\r\n");
      out.write("                </div>\r\n");
      out.write("   \t       </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입 신청서</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"\" >\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t<legend>회원가입 신청서</legend>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>이름</td>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>주민등록번호</td>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"number\" name=\"number\"> - <input type=\"text\" id=\"number\" name=\"number\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("    \t<td>아이디</td>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"id\" name=\"id\">korea</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"pw\" name=\"pw\">영문/숫자포함 6자 이상</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>비밀번호 힌트/답변</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("        <select name=\"pwhint\" id=\"pwhint\">\r\n");
      out.write("            <option value=\"v1\">선택하세요</option>\r\n");
      out.write("            <option value=\"v2\">내가 좋아하는 과일은</option>\r\n");
      out.write("            <option value=\"v2\">내 어릴적 별명은</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>답변</td>\r\n");
      out.write("        <td><input type=\"text\" id=\"pwanswer\" name=\"pwanswer\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>이메일</td>\r\n");
      out.write("        <td><input type=\"mail\" id=\"mail\" name=\"mail\">@<input type=\"mail\" id=\"mail\" name=\"mail\">\r\n");
      out.write("            <select name=\"pwhint\" id=\"pwhint\">\r\n");
      out.write("                <option value=\"v1\">선택하세요</option>\r\n");
      out.write("                <option value=\"v2\">hanmail.net</option>\r\n");
      out.write("                <option value=\"v2\">nate.com</option>\r\n");
      out.write("                <option value=\"v2\">naver.com</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>주소</td>\r\n");
      out.write("        <td>우편번호 <input type=\"text\" id=\"postnumber\" name=\"postnumber\"> <input type=\"text\" id=\"address\" name=\"address\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>전화번호</td>\r\n");
      out.write("        <td><input type=\"text\" id=\"telnumber\" name=\"telnumber\"> - <input type=\"text\" id=\"telnumber\" name=\"telnumber\"> - <input type=\"text\" id=\"telnumber\" name=\"telnumber\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t<td>핸드폰번호</td>\r\n");
      out.write("        <td><input type=\"text\" id=\"phone\" name=\"phone\"> - <input type=\"text\" id=\"phone\" name=\"phone\"> - <input type=\"text\" id=\"phone\" name=\"phone\"> </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>직업</td>\r\n");
      out.write("        <td>\r\n");
      out.write("        <select name=\"job\" id=\"job\">\r\n");
      out.write("            <option value=\"v1\">선택하세요</option>\r\n");
      out.write("            <option value=\"v2\">학생</option>\r\n");
      out.write("            <option value=\"v2\">회사원</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");

	String num1= request.getParameter("num1");
	String hel="Hello!";
	String wor="World";
	if(num1!=null){
		
		for(int i=1;i<=Integer.parseInt(num1); i++){
			out.print("<h" + i + ">"+ hello + " "+world + "</h" + i + ">");
			if(i==Integer.parseInt(num1)){

      out.write("\r\n");
      out.write("\t\t\t\t<h1> 스크립틀릿 내 for문의 마지막 수행입니다.</h1>\r\n");

			} else {

      out.write(" <h1>스크립틀릿 내 for문 수행중입니다.</h1>\r\n");

			}
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 int num = add(2, 3); 
      out.write('\r');
      out.write('\n');
      out.print( num );
      out.write("번 반복합니다.<br/>\r\n");
      out.print( add(2, 3) );
      out.write("\r\n");
      out.write("\r\n");

	for(int i =1; i<= num; i++) {

      out.write(' ');
      out.write(' ');
      out.print(hello);
      out.write(' ');
      out.print(world);
      out.write("<br/>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>request 내장객체를 이용한 요청 전송정보</title>\r\n");
      out.write("\r\n");
      out.write("요청 프로토콜 : ");
      out.print(request.getProtocol() );
      out.write("<br>\r\n");
      out.write("요청 방식 : ");
      out.print(request.getMethod() );
      out.write("<br>\r\n");
      out.write("현재 페이지 경로 : ");
      out.print(request.getContextPath() );
      out.write("<br>\r\n");
      out.write("웹 클라이언트 URI : ");
      out.print(request.getRequestURI() );
      out.write("<br>\r\n");
      out.write("웹 클라이언트 URL : ");
      out.print(request.getRequestURL() );
      out.write("<br>\r\n");
      out.write("웹 클라이언트 Query : ");
      out.print(request.getQueryString() );
      out.write("<br>\r\n");
      out.write("웹 클라이언트 호스트명 : ");
      out.print(request.getRemoteHost() );
      out.write("<br>\r\n");
      out.write("웹 클라이언트 IP 주소 : ");
      out.print(request.getRemoteAddr() );
      out.write("<br>\r\n");
      out.write("웹 서버 도메인 : ");
      out.print(request.getServerName() );
      out.write("<br>\r\n");
      out.write("웹 서버 포트 : ");
      out.print(request.getServerPort() );
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<p>헤더 정보</p>\r\n");
      out.write("\r\n");

Enumeration<String> header = request.getHeaderNames();

while(header.hasMoreElements()){
	String name = (String)header.nextElement();
	String value = request.getHeader(name);
	out.print(name + " : " + value + "<br>");
	
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"Jsp0516_date.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<label for=\"name\">이름</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"name\" name=\"name\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"전송\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");

String name = request.getParameter("name");
if(name != null){
	String naming=null;
	pageContext.forward("Jsp0516_chap6.jsp");

	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t포워딩 수행 후 메시지입니다.<br>\r\n");
      out.write("\t");
out.print("하나<br>"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
out.print("둘<br>"); 
      out.write('\r');
      out.write('\n');
      out.write('	');
out.print("셋<br>"); 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

	out.print("여기는 pageContextForwarded.jsp 페이지 입니다!"); 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
